config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "todos#index"
  resources :todos do
    member do
      post :toggle_check
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates_presence_of :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all

    if params[:id]
      @todo = Todo.find(params[:id])
    else
      @todo = Todo.new
    end
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.save

    # redirect_to todos_path
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])
    @todo.update_attributes(todo_params)
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
  end

  def toggle_check
    @todo = Todo.find(params[:id])
    # 當值是 boolean 的時候，可以使用 toggle 方法來切換 true/false
    # 加上驚歎號表示會直接存入資料庫（否則要另外 save)
    # ref: http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-toggle
    @todo.toggle!(:done)
    redirect_to todos_path
  end

  private

  def todo_params
    params.require(:todo).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ajax Todolist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_for @todo, { class: "my-form", remote: true } do |f| %>
  <div class="input-group">
    <%= f.text_area :title, :class => "form-control" %>
    <div class="input-group-addon">
      <%= f.submit "Update", :class => "my-btn my-btn-transparent" %>
    </div>
  </div>
<% end %>

app/views/todos/_todo.html.erb
<td class="my-pointer">
  <%= link_to toggle_check_todo_path(todo), id: "todo-check-#{todo.id}", method: :post do %>
    <% if todo.done? %>
      <span class="my-font glyphicon glyphicon-check"></span>
    <% else %>
      <span class="my-font glyphicon glyphicon-unchecked"></span>
    <% end %>
  <% end %>
</td>
<td>
  <p id="todo-title-<%= todo.id %>" class="title my-font">
    <%= todo.title %>
  </p>
</td>
<td class="my-operation">
  <%= link_to edit_todo_path(todo), remote: true do %>
    <span class="my-btn my-btn-transparent text-info glyphicon glyphicon-pencil"></span>
  <% end %>
  <%= link_to todo_path(todo), remote: true, method: :delete do %>
    <span class="my-btn my-btn-transparent text-danger glyphicon glyphicon-trash"></span>
  <% end %>
</td>

app/views/todos/create.js.erb
var todo = document.createElement("tr");
todo.id = "todo-<%= @todo.id %>";
todo.innerHTML = "<%= j render(:partial => "todo", :locals => { :todo => @todo }) %>";
$("#todolist").append(todo);

app/views/todos/destroy.js.erb
$("#todo-<%= @todo.id %>").remove();

app/views/todos/edit.js.erb
<% html = j( render :partial => "form", :locals => { :todo => @todo } ) %>
var todo_tds = $("#todo-<%= @todo.id %>").children();
$(todo_tds[1]).html("<%= html %>");

app/views/todos/index.html.erb
<div class="container">

  <h1 class="text-center">To Do List</h1>

  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title">事項清單</h3>
    </div>

    <!-- Add new todo -->
    <div class="panel-body">
    <%= form_for @todo, {class: "my-form", remote: true} do |f| %>
      <%= f.label "Add New To-Do" %>
      <div class="input-group">
        <%= f.text_area :title, :class => "form-control" %>
        <div class="input-group-addon">
          <%= f.submit "Create", :class => "my-btn my-btn-transparent" %>
        </div>
      </div>
      <% end %>
    </div>

    <!-- Todo List -->
    <table class="my-table table table-hover">
      <tbody id="todolist">
        <% @todos.each do |todo| %>
          <tr id="todo-<%= todo.id %>">
            <%= render :partial => "todo", :locals => { :todo => todo } %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/todos/update.js.erb
<% html = j( render :partial => "todo", :locals => { :todo => @todo } ) %>
$("#todo-<%= @todo.id %>").html("<%= html %>")